### ISSUE TITLE
Tracking issue: protocol version 0.4.

### ISSUE THREAD

**Issue by lyulka** [parallelchain-io/parallelchain-protocol#9]
# ParallelChain protocol version 0.4

This is a todo list of things we want to add/change in protocol version 0.4 before we freeze it as a release.

- [ ] Specify genesis state.
- [ ] Specify P2P networking.
- [ ] Specify “visibility byte” (#4).
- [ ] Specify that MPTs shouldn’t contain an extension node (#6).
- [ ] Specify Index Heap storage and operations sequence flow.
- [ ] Be more explicit in what steps are gas metered.
- [ ] Be more explicit in what things have to be Borsh-serialized.
